### ISSUE TITLE
InfluxDbEventListener refactoring

### ISSUE THREAD

**Issue by Algatux** [Algatux/influxdb-bundle#17]
InfluxDbEventListener uses deprecated services, must be refactored using the new services

**Comment by soullivaneuh** [comment]
BC or BC break way?

**Comment by Algatux** [comment]
I think I'll break

**Comment by soullivaneuh** [comment]
In this case, could you please push a `1.x` branch and make `master` for 2.x?

I can't solve #8 because because event listener are affected too: https://github.com/Algatux/influxdb-bundle/blob/1.0.1/src/Resources/config/listeners.xml#L11-L12

So I'll start it directly under master.

This mean you can push a 1.1 right now if you want. :+1:

**Comment by Algatux** [comment]
@Soullivaneuh done!

**Comment by Algatux** [comment]
I will wait for #21 to close this one, need to see the multi-database implementation
