### ISSUE TITLE
Including phpunit ad dev dependency causes CI to broke

### ISSUE THREAD

**Issue by Algatux** [Algatux/influxdb-bundle#72]
Including phpunit ad dev dependency causes CI to broke when the --prefer-lowest composer flag is applied

see dependecies_update branch

**Comment by soullivaneuh** [comment]
Is this issue still relevant? PHPUnit is not a dependency anymore here.

**Comment by Algatux** [comment]
I gas thinking to rei produce it because of some issues on ci

**Comment by Algatux** [comment]
I was thinking to reintroduce  it because of some issues on the ci In prefer lowest

**Comment by soullivaneuh** [comment]
What kind of issue do you have? The last build looks good: https://travis-ci.org/Algatux/influxdb-bundle/jobs/299017351

**Comment by Algatux** [comment]
If take a look at the log:

`$ vendor/bin/phpunit -c . --coverage-clover=./build/coverage/coverage.xml
PHPUnit 2.1.2-4-gac49e2a by Sebastian Bergmann and contributors.
...........................WWWWW..str_repeat(): Second argument has to be greater than or equal to 0`

Maybe it's a phpunit bug, dunno (look at the output and to phpunit version)

TAking a look to phpunit code it semmes that it takes the git tag version as his own version .... ugly!

**Comment by soullivaneuh** [comment]
Ok I don't understand. From where come this log? Travis does not use vendor phpunit bin.

You told:

> I was thinking to reintroduce it because of some issues on the ci In prefer lowest

But why re-introduce the phpunit as dependency if it is causing issue? ^^"

BTW, the phpunit from vendor is not reliable because the phpunit use dependency according to the `composer.json` and not the `composer.lock` file where phar are built. This is why it's recommended to use phar files IMO.

**Comment by soullivaneuh** [comment]
We can consider this issue as irrelevant anymore. PHPUnit is not a dev dependency anymore since the migration to GitHub actions (#99).
